config/routes.rb
Rails.application.routes.draw do
  mount InsteddTelemetry::Engine => '/instedd_telemetry'
  # We need to define devise_for just omniauth_callbacks:uth_callbacks otherwise it does not work with scoped locales
  # see https://github.com/plataformatec/devise/issues/2813
  devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks', sessions: 'sessions' }

  scope "(:locale)", :locale => /#{Locales.available.keys.join('|')}/ do
    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    devise_for :users, skip: :omniauth_callbacks, controllers: {registrations: "registrations", sessions: 'sessions'}
    guisso_for :user

    devise_scope :user do
      get "users/validate_credentials" => "registrations#validate_credentials"
    end


    # match 'messaging' => 'messaging#index'
    match 'nuntium' => 'nuntium#receive', :via => :post
    match 'authenticate' => 'nuntium#authenticate', :via => :post
    match 'android/collections' => 'android#collections_json', :via => :get
    match 'android/submission' => 'android#submission', :via => :post
    match 'collections/breadcrumbs' => 'collections#render_breadcrumbs', :via => :post
    match 'real-time-resource-tracking' => 'home#second_page', :via => :get
    match 'track-medical-supplies-and-personnel'=> 'home#medical_page', :via => :get
    match 'track-food-prices-and-supplies' => 'home#food_page', :via => :get
    #match 'analytics' => 'analytics#index', :via => :get

    match 'memberships/collections_i_admin' => 'memberships#collections_i_admin', :via => :get

    match 'collections/:id/import_layers_from/:other_id' => 'collections#import_layers_from', :via => :get

    resources :repeats

    resources :collections do
      post :register_gateways
      get  :message_quota
      get :sites_by_term

      get :current_user_membership

      resources :sites do
        member do
          post 'partial_update'
        end
      end
      resources :layers do
        member do
          put :set_order
        end
        collection do
          post :decode_hierarchy_csv
          post :order
        end
      end

      resources :fields do
        collection do
          get 'mapping'
        end
        member do
          get 'hierarchy'
        end
      end

      resources :memberships do
        collection do
          get 'invitable'
          get 'search'
          post 'set_layer_access_anonymous_user'
          post 'set_access_anonymous_user'
          delete :leave_collection
        end
        member do
          post 'set_access'
          #TODO: move set_layer_access to the more generic set_access
          post 'set_layer_access'
          post 'set_admin'
          post 'unset_admin'
        end
      end
      resources :sites_permission

      get 'members'
      get 'settings'
      get 'quotas'
      get 'csv_template'
      get 'max_value_of_property'

      post 'create_snapshot'
      post 'load_snapshot'
      post 'unload_current_snapshot'

      get 'recreate_index'
      get 'search'

      get 'sites_info'

      collection do
        post 'upload_logo'
      end

      resource :import_wizard, only: [] do
         get 'index'
         post 'upload_csv'
         post 'import_csv_from_google_spreadsheet'
         get 'adjustments'
         get 'guess_columns_spec'
         post 'execute'
         post 'validate_sites_with_columns'
         get 'get_visible_sites/:page' => 'import_wizards#get_visible_sites'
         get 'import_in_progress'
         get 'import_finished'
         get 'import_failed'
         get 'job_status'
         get 'cancel_pending_jobs'
         get 'logs'
       end
    end

    resources :sites do
      get 'root_sites'
      get 'search', :on => :collection

      post 'update_property'
    end

    resources :activities, :only => [:index], :path => 'activity'
    resources :quotas
    resources :gateways do
      post 'status', :on => :member
      post 'try'
    end

    match 'terms_and_conditions' => redirect("http://instedd.org/terms-of-service/"), :via => [:get, :post]

    scope '/plugin' do
      Plugin.all.each do |plugin|
        unless plugin.name == 'fred_api'
          scope plugin.name do
            plugin.hooks[:routes].each { |plugin_routes_block| instance_eval &plugin_routes_block }
          end
        end
      end
    end

    match '/locale/update' => 'locale#update',  :as => 'update_locale', :via => [:get, :post]
    root :to => 'home#index'
  end

  scope '/plugin' do
    Plugin.find_by_names('fred_api').each do |plugin|
      scope plugin.name do
        plugin.hooks[:routes].each { |plugin_routes_block| instance_eval &plugin_routes_block }
      end
    end
  end

  namespace :api do
    resources :collections, except: [:update] do
      resources :memberships, only: [:index, :create, :destroy] do
        member do
          post :set_admin
          post :unset_admin
        end
        collection do
          get 'invitable'
        end
      end

      resources :layers, except: [:show, :new, :edit] do
        resources :fields, only: [:create]
      end

      resources :fields, only: [:index] do
        collection do
          get 'mapping'
        end
      end

      member do
        get 'sample_csv', as: :sample_csv
        get 'count', as: :count
        get 'geo', as: :geojson, to: "collections#geo_json"
        post 'sites', to: 'sites#create'
        post 'update_sites', to: 'collections#bulk_update'
      end
    end

    resources :sites, only: [:show, :destroy, :update] do
      member do
        post :update_property
        post :partial_update
      end
    end
    get 'histogram/:field_id', to: 'collections#histogram_by_field', as: :histogram_by_field
    get 'collections/:collection_id/sites/:id/histories' => 'sites#histories', as: :histories
    get 'activity' => 'activities#index', as: :activity
    resources :tokens, :only => [:index, :destroy]
  end

  admin_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.is_super_user?
  end

  constraints admin_constraint do
    mount Resque::Server, :at => "/admin/resque"
    match 'analytics' => 'analytics#index', :via => :get
    match 'quota' => 'quota#index', via: :get
  end

  # TODO: deprecate later
  match 'collections/:collection_id/fred_api/v1/facilities/:id' => 'fred_api#show_facility', :via => :get
  match 'collections/:collection_id/fred_api/v1/facilities' => 'fred_api#facilities', :via => :get
  match 'collections/:collection_id/fred_api/v1/facilities/:id' => 'fred_api#delete_facility', :via => :delete
  match 'collections/:collection_id/fred_api/v1/facilities' => 'fred_api#create_facility', :via => :post
  match 'collections/:collection_id/fred_api/v1/facilities/:id(.:format)' => 'fred_api#update_facility', :via => :put
end

app/models/collection/elasticsearch_concern.rb
module Collection::ElasticsearchConcern
  extend ActiveSupport::Concern

  included do
    after_create :create_index
    after_destroy :destroy_index
  end

  def create_index
    index_properties = {
      refresh: true,
      mappings: { site: site_mapping }
    }
    index_properties.merge!(Site::IndexUtils::DefaultIndexSettings)

    result = Elasticsearch::Client.new.indices.create index: index_name, body: index_properties

    unless result["acknowledged"]
      error = "Can't create index for collection #{name} (ID: #{id})."
      Rails.logger.error error
      Rails.logger.error "ElasticSearch response was: #{result}."
      raise error
    end

    # This is because in the tests collections are created and the
    # fields association will almost always be empty, but it needs to
    # be refreshed afte creating layers and fields.
    clear_association_cache if Rails.env.test?
  end

  def site_mapping
    Site::IndexUtils.site_mapping(fields)
  end

  def update_mapping
    client = Elasticsearch::Client.new
    client.indices.put_mapping index: index_name, type: 'site', body: {site: site_mapping}
    client.indices.refresh index: index_name
  end

  def recreate_index
    destroy_index rescue nil
    create_index

    client = Elasticsearch::Client.new

    docs = sites.with_deleted.map do |site|
      site.collection = self
      site.to_elastic_search
    end
    docs.each_slice(1000) do |docs_slice|
      ops = []
      docs_slice.each do |doc|
        ops.push index: { _index: index_name, _type: 'site', _id: doc[:id]}
        ops.push doc
      end
      client.bulk body: ops
    end
    client.indices.refresh index: index_name
  end

  def destroy_index
    Elasticsearch::Client.new.indices.delete index: index_name
  end

  def index_name(options = {})
    self.class.index_name id, options
  end

  def new_search(options = {})
    Search.new(self, options)
  end

  def elasticsearch_count
    client = Elasticsearch::Client.new
    if block_given?
      value = client.count index: index_name, body: yield
    else
      value = client.count index: index_name
    end
    value["count"]
  end

  def new_map_search
    MapSearch.new id
  end

  def index_names_with_options(options = {})
    self.class.index_names_with_options(id, options)
  end

  module ClassMethods
    INDEX_NAME_PREFIX = Rails.env == 'test' ? "collection_test" : "collection"

    def index_name(id, options = {})
      if options[:snapshot_id]
        return "#{INDEX_NAME_PREFIX}_#{id}_#{options[:snapshot_id]}"
      end

      if options[:user]
        snapshot = Collection.find(id).snapshot_for(options[:user])
        if snapshot
          return "#{INDEX_NAME_PREFIX}_#{id}_#{snapshot.id}"
        end
      end

      "#{INDEX_NAME_PREFIX}_#{id}"
    end

    def index_names_with_options(*ids, options)
      # If we want the indices for many collections for a given user, it's faster
      # to get all snapshots ids first instead of fetching them one by one for each collection.
      # This optimization does that.
      if options[:user] && !options[:snapshot_id]
        collection_ids_to_snapshot_id = Snapshot.ids_for_collections_ids_and_user(ids, options[:user])
        options.delete :user
      end

      index_names = ids.map do |id|
        if collection_ids_to_snapshot_id
          options[:snapshot_id] = collection_ids_to_snapshot_id[id.to_i]
        end

        index_name(id, options)
      end
      index_names.join ","
    end
  end
end

app/models/collection/import_layers_schema_concern.rb
module Collection::ImportLayersSchemaConcern
	def import_schema(layers_string, user)
		layers_json = JSON.parse layers_string
		layers_json.each do |layer_json|
			params = layer_json.except(*["id", "created_at", "updated_at", "fields"])
			layer = layers.new params
			layer.user = user
			if layer_json["fields"]
				layer_json["fields"].each do |field_json|
					field_params = field_json.except(*["id", "created_at", "updated_at", "collection_id"])
					field = layer.fields.new field_params
					field.collection_id = self.id
				end
			end
			layer.save!
		end
	end
end

app/controllers/api/collections_controller.rb
class Api::CollectionsController < ApiController
  include Api::JsonHelper
  include Api::GeoJsonHelper

  authorize_resource :collection, :decent_exposure => true, only: [:destroy]

  before_action :authenticate_collection_user!, :except => [:create, :show, :index]

  expose(:collection) { Collection.find(params[:collection_id] || params[:id]) }

  def index
    collections = current_user.collections
    render_json collections_json(collections, collections.count_sites)
  end

  def create
    coll_params = params[:collection]
    coll_params[:icon] ||= 'default'

    new_collection = Collection.new params[:collection]

    current_user.create_collection new_collection
    current_user.collection_count += 1
    current_user.update_successful_outcome_status
    current_user.save!
    render_json new_collection
  end

  def show
    authorize! :export, collection

    options = [:sort]

    if params[:format] == 'csv' || params[:page] == 'all'
      options << :all
      params.delete(:page)
    else
      options << :page
    end

    results = build_search(*options).mapped_results
    human = Field.yes?(params[:human])

    respond_to do |format|
      format.rss {
        @results = results.for_json(human)
        render :show, layout: false
      }
      format.csv {
        sites_csv = collection.to_csv(results.for_csv(human), results.visible_fields)
        send_data sites_csv, type: 'text/csv', filename: "#{collection.name}_sites.csv"
      }
      format.json {
        render_json collection_json(collection, results.for_json(human))
      }
    end
  end

  def sample_csv
    respond_to do |format|
      format.csv { collection_sample_csv(collection) }
    end
  end

  def collection_sample_csv(collection)
    sample_csv = collection.sample_csv current_user
    send_data sample_csv, type: 'text/csv', filename: "#{collection.name}_sites.csv"
  end

  def count
    render_json perform_search(:count).total
  end

  def histogram_by_field
    fields = collection.fields.where(code: params[:field_id])
    fields = collection.fields.where(id: params[:field_id]) if fields.empty?

    raise "Field not found" if fields.empty?

    filters = find_fields(params[:filters])

    render_json perform_histogram_search(fields.first, filters)
  end

  def geo_json
    @results = perform_search :page, :sort, :require_location
    respond_to do |format|
      format.json { render_json collection_geo_json(collection, @results) }
    end
  end

  def destroy
    collection.destroy
    head :ok
  end

  def bulk_update
    properties_to_update = params[:updates].deep_dup
    properties_to_update.delete(:properties)
    field_codes = collection.es_codes_by_field_code
    if params[:updates][:properties]
      properties_to_update[:properties] = {}
      params[:updates][:properties].each do |code, value|
        properties_to_update[:properties][field_codes[code]] = value
      end
    end
    params.delete(:updates)
    search = build_search :all
    ids = search.results.map{|s| s["_id"].to_i}
    collection.sites.where(id: ids).each do |s|
      s.validate_and_process_parameters(properties_to_update, current_user)
      s.user = current_user
      s.save
    end
    head :ok
  end

  private

  def perform_histogram_search(field, filters=nil)
    search = new_search
    search.histogram_search(field.es_code, filters)
    search.histogram_results(field.es_code)
  end

  def perform_search(*options)
    search = build_search(*options)
    search.api_results
  end

  def build_search(*options)
    except_params = [:action, :controller, :format, :id, :site_id, :updated_since, :deleted_since, :search, :box, :lat, :lng, :radius, :fields, :name, :sitename, :page_size, :location_missing, :locale, :human, :created_since]

    # cache all fields to accelerate condition building
    collection.fields.each {|field| field.cache_for_read}
    search = new_search

    search.use_codes_instead_of_es_codes

    if options.include? :page
      search.page_size = params[:page_size].to_i if params[:page_size]
      search.page params[:page].to_i if params[:page]
      if !params[:page] && !params[:page_size]
        search.page 1
      end
      except_params << :page
    elsif options.include? :count
      search.offset 0
      search.limit 0
    elsif options.include? :all
      search.unlimited
    else
      search.page 1
    end

    search.id(params[:site_id]) if params[:site_id]
    search.after params[:updated_since] if params[:updated_since]
    search.created_after params[:created_since] if params[:created_since]
    search.deleted_since params[:deleted_since] if params[:deleted_since]
    search.full_text_search params[:search] if params[:search]
    search.box(*valid_box_coordinates) if params[:box]
    search.select_fields(params[:fields]) if params[:fields]
    search.name(params[:name]) if params[:name]
    search.name_start_with(params[:sitename]) if params[:sitename]
    search.location_missing if params[:location_missing].present?

    if params[:lat] || params[:lng] || params[:radius]
      [:lat, :lng, :radius].each do |key|
        raise "Missing '#{key}' parameter" unless params[key]
        raise "Missing '#{key}' value" unless !params[key].blank?
      end
      search.radius params[:lat], params[:lng], params[:radius]
    end

    if options.include? :require_location
      search.require_location
    end

    if options.include? :sort
      search.sort params[:sort], params[:sort_direction] != 'desc' if params[:sort]
      except_params << :sort
      except_params << :sort_direction
    end

    search.where params.except(*except_params).to_h
    search
  end

  def valid_box_coordinates
    coords = params[:box].split ','
    raise "Expected the 'box' parameter to be four comma-separated numbers" if coords.length != 4

    coords.each_with_index do |coord, i|
      Float(coord) rescue raise "Expected #{(i + 1).ordinalize} value of 'box' parameter to be a number, not '#{coord}'"
    end

    coords
  end

  def find_fields(params)
    return nil if params.nil?
    replaced_params = {}
    params = JSON.parse(params) unless params.respond_to?(:each)
    params.each do |k,v|
      field = collection.fields.where(code: k).first
      replaced_params[field] = v
    end
    replaced_params
  end
end

app/views/collections/_form.haml
#settings
  = form_for collection, html: {style: "width: 960px;"}  do |f|
    :javascript
      $(document).ready(function(){ var select_icon = $('#select_icon');
        if(select_icon.val() == "")
          select_icon.val('default');
        $("#focus_icon").val(select_icon.val());
        $('.' + select_icon.val()).css({backgroundColor: '#D2D2D2', border: '1px solid #565656'});

        $("button").click(function(){
          if (this != $('.white')[0]){
            $('.' + $('#focus_icon').val()).css({backgroundColor: '#f5f5f5', border: '1px solid white'});
            this.style.backgroundColor =  "#D2D2D2";
            this.style.border =  "1px solid #565656";
            $("#focus_icon").val(this.classList["0"]);
          }else{
            $('#select_icon').val($("#focus_icon").val());
          }
        });
      });

    .field.w60
      = f.label :name
      = f.text_field :name, :readonly => !creation && (cannot? :update, collection)
      - if f.object.errors[:name].present?
        %label.error= "#{_("Collection|Name")} #{f.object.errors[:name].join(', ')}"
    .field.w60
      = f.label :description, _("Description")
      = f.text_area :description, rows: 3, :readonly =>  !creation && (cannot? :update, collection)

    = render partial: 'logo', locals: {form: f, logo: collection.logo, updateable: (creation || can?(:update, collection))}

    .field.w60
      %label
        Icon
      = render 'icon_selector', :f => f
    .w60
    %br{clear: :all}

    - if (creation || can?(:update, collection))
      = f.button _('Save'), :class => 'white'
      = link_to _('Cancel'), collection, :class=> 'grey'

app/views/collections/_icon_selector.haml
= f.hidden_field :icon, id: 'select_icon'
%input#focus_icon{:type =>"hidden"}

%button.default{:type => "button"}
%button.aed-2{:type => "button"}
%button.construction{:type => "button"}
%button.daycare{:type => "button"}
%button.drugstore{:type => "button"}
%button.fetalalcoholsyndrom{:type => "button"}
%button.firstaid{:type => "button"}
%button.hospital-building{:type => "button"}
%button.medicine{:type => "button"}
%button.nanny{:type => "button"}
%button.nursery{:type => "button"}
%button.villa{:type => "button"}
%br
%br
%br
%button.army{:type => "button"}
%button.bomber-2{:type => "button"}
%button.chemistry-2{:type => "button"}
%button.constructioncrane{:type => "button"}
%button.cycling{:type => "button"}
%button.dentist{:type => "button"}
%button.disability{:type => "button"}
%button.factory{:type => "button"}
%button.fishing{:type => "button"}
%button.foodtruck{:type => "button"}
%button.footprint{:type => "button"}
%button.fourbyfour{:type => "button"}
%br
%br
%br
%button.gay-female{:type => "button"}
%button.gay-male{:type => "button"}
%button.highschool{:type => "button"}
%button.school{:type => "button"}
%button.university{:type => "button"}
%button.hiking{:type => "button"}
%button.horseriding{:type => "button"}
%button.hostel_0star{:type => "button"}
%button.hotel_0star{:type => "button"}
%button.lodging_0star{:type => "button"}
%button.motel-2{:type => "button"}
%button.youthhostel{:type => "button"}
%br
%br
%br
%button.mastcrane1{:type => "button"}
%button.ophthalmologist{:type => "button"}
%button.powerlinepole{:type => "button"}
%button.poweroutage{:type => "button"}
%button.powerplant{:type => "button"}
%button.powersubstation{:type => "button"}
%button.radio-station-2{:type => "button"}
%button.windturbine{:type => "button"}
%button.mobilephonetower{:type => "button"}
%button.restaurant_fish{:type => "button"}
%button.sawmill-2{:type => "button"}
%button.mine{:type => "button"}
%br
%br
%br
%button.septic_tank{:type => "button"}
%button.shootingrange{:type => "button"}
%button.hunting{:type => "button"}
%button.solarenergy{:type => "button"}
%button.sozialeeinrichtung{:type => "button"}
%button.summercamp{:type => "button"}
%button.veterinary{:type => "button"}
%button.watertower{:type => "button"}
%button.wifi{:type => "button"}
%button.medicalstore{:type => "button"}
%button.recycle{:type => "button"}
%button.resort{:type => "button"}
%br
%br
%br

app/views/collections/_logo.haml
- if updateable
  #logo-editor.field.w60.hidden-until-loaded
    = label_tag :logo, _("Adjust logo")
    = image_tag logo.try(:url, :croppable).to_s, id: 'cropbox'

    #logo-preview
      %label Preview
      #preview-container
        = image_tag logo.try(:url, :preview).to_s, id: 'preview'

- if logo.present?
  #logo-display.field.w60
    = label_tag :logo
    .logo-border
      = image_tag logo.url(:grayscale), id: 'logo'

    %a#edit-logo-button.fedit{:href => '#'} Adjust

- if updateable
  .field.w60
    = label_tag :logo, _("Upload new logo")
    = file_field_tag :logo, id: 'logo-file-upload',
                            'data-url' => upload_logo_collections_path,
                            'accept' => 'image/*'

  = form.hidden_field :logo_cache
  - %w(x y w h).each do |attr|
    = form.hidden_field "crop_#{attr}"

app/views/collections/_snapshot.haml
%hr.clear/
%h2(id='snapshots') Snapshots
%p This will allow you to browse data in the future as it is looking right now.
- if collection_admin?

  = form_for(@snapshot, :url => collection_create_snapshot_path(collection)) do |f|
    %span.snapshot_name_field.w30
      = f.text_field :name, :placeholder => _("Enter Snapshot name")
      - if f.object.errors[:name].present?
        %br/
        %label.error= "Name #{f.object.errors[:name].join(', ')}"
    %button.icon_button.fsnapshot
      Take new snapshot

- if collection.snapshots.count > 0
  %table
    %tr
      = form_tag(collection_unload_current_snapshot_path(collection)) do
        %td.w30
          .snapshot_info{:class => if current_user_snapshot.at_present? then "active rounded" end}
            = radio_button_tag(:snapshot_id, "", current_user_snapshot.at_present?, :onclick => "this.form.submit();")
            = label_tag :snapshot_id_, _("Present time")
        %td

    - collection.snapshots.each do |snapshot|
      %tr
        = form_tag(collection_load_snapshot_path(collection)) do
          - is_current_snapshot = !current_user_snapshot.at_present? && current_user_snapshot.snapshot.id == snapshot.id
          %td.w30
            .snapshot_info{:class => if is_current_snapshot then "active rounded" end}
              = radio_button_tag(:snapshot_id, snapshot.id, is_current_snapshot, :onclick => "this.form.submit();")
              = label_tag "snapshot_id_#{snapshot.id}", snapshot.name
          %td.grey
            = label_tag :date, snapshot.date.rfc822
- elsif !collection_admin?
  There are no snapshots for this collection.

%br/
%br/

app/views/collections/bulk_update.haml
:javascript
  $(function() { $('#upload').change(function() { $('#upload_form').submit() }); });

= render 'tabs'

.tabsline
  %h2 Bulk update
  %p First, upload your CSV file

  %form#upload_form{action: collection_bulk_update_upload_csv_path(collection), method: :post, enctype: 'multipart/form-data'}
    %input{type: :hidden, name: 'authenticity_token', value: form_authenticity_token}
    %input#upload{type: :file, name: :file}

app/views/collections/import_wizard.haml
:javascript
  $(function() { $('#upload').change(function() { $('#upload_form').submit() }); });

= render 'tabs'

.tabsline
  %h2 Import wizard
  %p This wizard will guide you through importing a CSV file
  %br/

  - if current_snapshot
    = render '/current_snapshot_message'
  - else
    = render 'steps', :step => 1
    %br

    %h2.orange Upload your CSV file
    .box.plain.grey{:style => 'width: 66%'}
      .black We recommend you to download the CSV, make changes to it and upload it here for doing a bulk update:
      %ul
        %li Remove rows for sites you are not interested in updating
        %li Add rows for new sites
        %li Remove columns for fields you are not interested in updating
        %li Add columns for new fields

    - if collection.sites.exists?
      = link_to 'Download a CSV with all the sites in this collection', api_collection_path(collection, format: "csv"), class: "icon fimport black"
    -else
      = link_to 'Download a template CSV file', api_sample_csv_path(collection, format: 'csv'), class: "icon fimport black"

    %form#upload_form{action: collection_import_wizard_upload_csv_path(collection), method: :post, enctype: 'multipart/form-data'}
      %input{type: :hidden, name: 'authenticity_token', value: form_authenticity_token}
      .icon.fexport.black Upload a CSV file to update multiple sites
      %input#upload{type: :file, name: :file}

app/views/collections/new.haml
%h2 Create new collection
%p Define basic information about this collection
%br/

= render 'form', creation: true

app/views/collections/settings.haml
= render '/tabs'

.tabsline
  %h2 Settings
  %p Change basic information about this collection
  %br/

  = render 'form', creation: false

app/views/collections/show.haml
= render '/tabs'

- sites_count = if !current_user_snapshot.at_present? then collection.site_histories.at_date(current_user_snapshot.snapshot.date).count else collection.sites.count end

.tabsline
  %h2 Status
  %div
    .sbox.grey.w30.sitesBox
      .left.sitesDescription
        .sitesCount= sites_count
        sites
      %button.csvDownload.white.right{type: "button", |
          onclick: "window.location = '#{sites_count == 0 ? sample_csv_api_collection_path(collection, format: 'csv') : api_collection_path(collection, format: 'csv')}'"}
        = if sites_count == 0 then _('Download sample CSV') else _('Download as CSV') end
    - if any_update_permissions? collection, current_user
      %div
        = link_to _('Upload it for bulk sites updates'), collection_import_wizard_path(collection), class: 'icon fexport black'
  %hr.clear/
  %h2 API access
  %p{style: 'margin:-8px 0 8px 0'}
    Access the API in
    #{link_to('RSS', api_collection_path(collection, format: :rss), target: :_blank)},
    #{link_to('JSON', api_collection_path(collection, format: :json), target: :_blank)},
    or
    #{(link_to 'CSV', api_collection_path(collection, format: :csv), target: :_blank)}.
    Check the
    #{link_to('API documentation', 'https://github.com/instedd/resourcemap/wiki/REST_API', target: :_blank)}
    %br/
    %br/

  - if Settings.is_on?(:snapshot) && any_update_permissions?(collection, current_user)
    = render 'snapshot'

  %hr.clear/

  .delete-collection-or-sites
    - if collection_admin?
      .left
        = render './confirm_box', :action_code => 'delete-collection-sites', :action_description => _("Delete this collection's sites"), :icon_class => 'fclose', :confirm_action_prompt => _("Are you sure you want to delete this collection's sites?"), :action_url => collection_path(only_sites: true)

      .left
        = render './confirm_box', :action_code => 'delete-collection', :action_description => _('Delete collection'), :icon_class => 'fdelete', :confirm_action_prompt => _('Are you sure you want to delete this collection? All sites, layers, fields, memberships and activities will also be deleted.'), :action_url => collection_path
    .left
      = render './confirm_box', :action_code => 'leave-collection', :action_description => _("Leave collection"), :icon_class => 'fleave', :confirm_action_prompt => _("Are you sure you want to leave this collection? You will not be able to access it anymore"), :action_url => leave_collection_collection_memberships_path(collection)

app/views/collections/sites.haml
- content_for :head do
  = google_maps_javascript_include_tag
  :javascript
    $(function() {
      var myOptions = {
        center: new google.maps.LatLng(-34.397, 150.644),
        zoom: 8,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      var map = new google.maps.Map(document.getElementById("map"), myOptions);
    });

= render '/tabs'

.tabsline
  %table
    %tr{valign: :top}
      %td
        South America
      %td
        #map{style: 'width: 600px; height: 300px'}